/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/

#ifndef QML_ZEBRA_PLUGIN_H
#define QML_ZEBRA_PLUGIN_H

#include <QQmlExtensionPlugin>
#include <qqml.h>

class QmlXrapMsg;
class QmlXrapMsgAttached;
class QmlZebHandler;
class QmlZebHandlerAttached;

#include "QmlXrapMsg.h"
#include "QmlZebHandler.h"

class QmlZebraPlugin : public QQmlExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA (IID "org.qt-project.Qt.QQmlExtensionInterface")
    
public:
    void registerTypes (const char *uri)
    {
        qmlRegisterType<QmlXrapMsg> (uri, 1, 0, "QmlXrapMsg");
        qmlRegisterType<QmlXrapMsgAttached>();
        qmlRegisterType<QmlZebHandler> (uri, 1, 0, "QmlZebHandler");
        qmlRegisterType<QmlZebHandlerAttached>();
    };
};

#endif

/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
