/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/

#include "QmlZebHandler.h"



QObject* QmlZebHandler::qmlAttachedProperties(QObject* object) {
    return new QmlZebHandlerAttached(object);
}


///
//  Add a new offer this handler will handle. Returns 0 if successful,
//  otherwise -1.                                                     
//  The content type parameter is optional and is used to             
//  filter requests upon their requested (GET) or provided (POST/PUT) 
//  content's type. The content type parameter may be a regex. If the 
//  request's content type does not match it is automatically rejected
//  with the error code 406 (Not acceptable).                         
int QmlZebHandlerAttached::addOffer (zactor_t *self, int method, const QString &uri, const QString &contentType) {
    return zeb_handler_add_offer (self, method, uri.toUtf8().data(), contentType.toUtf8().data());
};

///
//  Self test of this class.
void QmlZebHandlerAttached::test (bool verbose) {
    zeb_handler_test (verbose);
};

/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
