/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/

#include "QmlZebHandler.h"



QObject* QmlZebHandler::qmlAttachedProperties(QObject* object) {
    return new QmlZebHandlerAttached(object);
}


///
//  Add a new offer this handler will handle. Returns 0 if successful,
//  otherwise -1.                                                     
int QmlZebHandlerAttached::addOffer (zactor_t *self, int method, const QString &uri) {
    return zeb_handler_add_offer (self, method, uri.toUtf8().data());
};

///
//  Add a new accept type that this handler can deliver. May be a regular
//  expression. Returns 0 if successfull, otherwise -1.                  
int QmlZebHandlerAttached::addAccept (zactor_t *self, const QString &accept) {
    return zeb_handler_add_accept (self, accept.toUtf8().data());
};

///
//  Self test of this class.
void QmlZebHandlerAttached::test (bool verbose) {
    zeb_handler_test (verbose);
};

/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
