################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################

include(FindPkgConfig)
PKG_CHECK_MODULES(PC_LIBMICROHTTPD "libmicrohttpd")
IF (NOT PC_LIBMICROHTTPD_FOUND)
    PKG_CHECK_MODULES(PC_LIBMICROHTTPD "libmicrohttpd")
ENDIF (NOT PC_LIBMICROHTTPD_FOUND)

# some libraries install the headers is a subdirectory of the include dir
# returned by pkg-config, so use a wildcard match to improve chances of finding
# headers and SOs.
find_path(
    LIBMICROHTTPD_INCLUDE_DIRS
    NAMES libmicrohttpd.h
    HINTS ${PC_LIBMICROHTTPD_INCLUDE_DIRS} ${PC_LIBMICROHTTPD_INCLUDE_DIRS}/*
)

find_library(
    LIBMICROHTTPD_LIBRARIES
    NAMES libmicrohttpd
    HINTS ${PC_LIBMICROHTTPD_LIBRARY_DIRS} ${PC_LIBMICROHTTPD_LIBRARY_DIRS}/*
)

IF (NOT LIBMICROHTTPD_INCLUDE_DIRS STREQUAL LIBMICROHTTPD_INCLUDE_DIRS-NOTFOUND AND NOT LIBMICROHTTPD_LIBRARIES STREQUAL LIBMICROHTTPD_LIBRARIES-NOTFOUND)
    include(FindPackageHandleStandardArgs)
    FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBMICROHTTPD DEFAULT_MSG LIBMICROHTTPD_LIBRARIES LIBMICROHTTPD_INCLUDE_DIRS)
    mark_as_advanced(LIBMICROHTTPD_LIBRARIES LIBMICROHTTPD_INCLUDE_DIRS)
ENDIF (NOT LIBMICROHTTPD_INCLUDE_DIRS STREQUAL LIBMICROHTTPD_INCLUDE_DIRS-NOTFOUND AND NOT LIBMICROHTTPD_LIBRARIES STREQUAL LIBMICROHTTPD_LIBRARIES-NOTFOUND)

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
