################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################

include(FindPkgConfig)
PKG_CHECK_MODULES(PC_LIBCURL "libcurl")
IF (NOT PC_LIBCURL_FOUND)
    PKG_CHECK_MODULES(PC_LIBCURL "libcurl")
ENDIF (NOT PC_LIBCURL_FOUND)

# some libraries install the headers is a subdirectory of the include dir
# returned by pkg-config, so use a wildcard match to improve chances of finding
# headers and SOs.
find_path(
    LIBCURL_INCLUDE_DIRS
    NAMES libcurl.h
    HINTS ${PC_LIBCURL_INCLUDE_DIRS} ${PC_LIBCURL_INCLUDE_DIRS}/*
)

find_library(
    LIBCURL_LIBRARIES
    NAMES libcurl
    HINTS ${PC_LIBCURL_LIBRARY_DIRS} ${PC_LIBCURL_LIBRARY_DIRS}/*
)

IF (NOT LIBCURL_INCLUDE_DIRS STREQUAL LIBCURL_INCLUDE_DIRS-NOTFOUND AND NOT LIBCURL_LIBRARIES STREQUAL LIBCURL_LIBRARIES-NOTFOUND)
    ADD_DEFINITIONS(-DHAVE_LIBCURL)

    include(FindPackageHandleStandardArgs)
    FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBCURL DEFAULT_MSG LIBCURL_LIBRARIES LIBCURL_INCLUDE_DIRS)
    mark_as_advanced(LIBCURL_LIBRARIES LIBCURL_INCLUDE_DIRS)
ENDIF (NOT LIBCURL_INCLUDE_DIRS STREQUAL LIBCURL_INCLUDE_DIRS-NOTFOUND AND NOT LIBCURL_LIBRARIES STREQUAL LIBCURL_LIBRARIES-NOTFOUND)

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
