################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################

include(FindPkgConfig)
PKG_CHECK_MODULES(PC_CURL "libcurl")
IF (NOT PC_CURL_FOUND)
    PKG_CHECK_MODULES(PC_CURL "curl")
ENDIF (NOT PC_CURL_FOUND)

# some libraries install the headers is a subdirectory of the include dir
# returned by pkg-config, so use a wildcard match to improve chances of finding
# headers and SOs.
find_path(
    CURL_INCLUDE_DIRS
    NAMES curl.h
    HINTS ${PC_CURL_INCLUDE_DIRS} ${PC_CURL_INCLUDE_DIRS}/*
)

find_library(
    CURL_LIBRARIES
    NAMES curl
    HINTS ${PC_CURL_LIBRARY_DIRS} ${PC_CURL_LIBRARY_DIRS}/*
)

IF (NOT CURL_INCLUDE_DIRS STREQUAL CURL_INCLUDE_DIRS-NOTFOUND AND NOT CURL_LIBRARIES STREQUAL CURL_LIBRARIES-NOTFOUND)
    ADD_DEFINITIONS(-DHAVE_LIBCURL)

    include(FindPackageHandleStandardArgs)
    FIND_PACKAGE_HANDLE_STANDARD_ARGS(CURL DEFAULT_MSG CURL_LIBRARIES CURL_INCLUDE_DIRS)
    mark_as_advanced(CURL_LIBRARIES CURL_INCLUDE_DIRS)
ENDIF (NOT CURL_INCLUDE_DIRS STREQUAL CURL_INCLUDE_DIRS-NOTFOUND AND NOT CURL_LIBRARIES STREQUAL CURL_LIBRARIES-NOTFOUND)

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
