################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################

require 'ffi'
require_relative 'ffi/version'

module Zebra
  module FFI
    module LibC
      extend ::FFI::Library
      ffi_lib ::FFI::Platform::LIBC
      attach_function :free, [ :pointer ], :void, blocking: true
    end

    extend ::FFI::Library

    def self.available?
      @available
    end

    begin
      lib_name = 'libzebra'
      lib_paths = ['/usr/local/lib', '/opt/local/lib', '/usr/lib64']
        .map { |path| "#{path}/#{lib_name}.#{::FFI::Platform::LIBSUFFIX}" }
      ffi_lib lib_paths + [lib_name]
      @available = true
    rescue LoadError
      warn ""
      warn "WARNING: ::Zebra::FFI is not available without libzebra."
      warn ""
      @available = false
    end

    if available?
      opts = {
        blocking: true  # only necessary on MRI to deal with the GIL.
      }

      attach_function :zeb_handler_add_offer, [:pointer, :int, :string], :int, **opts
      attach_function :zeb_handler_add_accept, [:pointer, :string], :int, **opts
      attach_function :zeb_handler_test, [:bool], :void, **opts

      require_relative 'ffi/zeb_handler'

      attach_function :xrap_msg_new, [:int], :pointer, **opts
      attach_function :xrap_msg_destroy, [:pointer], :void, **opts
      attach_function :xrap_msg_decode, [:pointer], :pointer, **opts
      attach_function :xrap_msg_encode, [:pointer], :pointer, **opts
      attach_function :xrap_msg_recv, [:pointer], :pointer, **opts
      attach_function :xrap_msg_recv_nowait, [:pointer], :pointer, **opts
      attach_function :xrap_msg_send, [:pointer, :pointer], :int, **opts
      attach_function :xrap_msg_send_again, [:pointer, :pointer], :int, **opts
      attach_function :xrap_msg_id, [:pointer], :int, **opts
      attach_function :xrap_msg_set_id, [:pointer, :int], :void, **opts
      attach_function :xrap_msg_parent, [:pointer], :string, **opts
      attach_function :xrap_msg_set_parent, [:pointer, :string, :varargs], :void, **opts
      attach_function :xrap_msg_content_type, [:pointer], :string, **opts
      attach_function :xrap_msg_set_content_type, [:pointer, :string, :varargs], :void, **opts
      attach_function :xrap_msg_content_body, [:pointer], :string, **opts
      attach_function :xrap_msg_set_content_body, [:pointer, :string, :varargs], :void, **opts
      attach_function :xrap_msg_status_code, [:pointer], :uint16, **opts
      attach_function :xrap_msg_set_status_code, [:pointer, :uint16], :void, **opts
      attach_function :xrap_msg_location, [:pointer], :string, **opts
      attach_function :xrap_msg_set_location, [:pointer, :string, :varargs], :void, **opts
      attach_function :xrap_msg_etag, [:pointer], :string, **opts
      attach_function :xrap_msg_set_etag, [:pointer, :string, :varargs], :void, **opts
      attach_function :xrap_msg_date_modified, [:pointer], :uint64, **opts
      attach_function :xrap_msg_set_date_modified, [:pointer, :uint64], :void, **opts
      attach_function :xrap_msg_resource, [:pointer], :string, **opts
      attach_function :xrap_msg_set_resource, [:pointer, :string, :varargs], :void, **opts
      attach_function :xrap_msg_parameters, [:pointer], :pointer, **opts
      attach_function :xrap_msg_get_parameters, [:pointer], :pointer, **opts
      attach_function :xrap_msg_set_parameters, [:pointer, :pointer], :void, **opts
      attach_function :xrap_msg_parameters_string, [:pointer, :string, :string], :string, **opts
      attach_function :xrap_msg_parameters_insert, [:pointer, :string, :string, :varargs], :void, **opts
      attach_function :xrap_msg_if_modified_since, [:pointer], :uint64, **opts
      attach_function :xrap_msg_set_if_modified_since, [:pointer, :uint64], :void, **opts
      attach_function :xrap_msg_if_none_match, [:pointer], :string, **opts
      attach_function :xrap_msg_set_if_none_match, [:pointer, :string, :varargs], :void, **opts
      attach_function :xrap_msg_metadata, [:pointer], :pointer, **opts
      attach_function :xrap_msg_get_metadata, [:pointer], :pointer, **opts
      attach_function :xrap_msg_set_metadata, [:pointer, :pointer], :void, **opts
      attach_function :xrap_msg_metadata_string, [:pointer, :string, :string], :string, **opts
      attach_function :xrap_msg_metadata_insert, [:pointer, :string, :string, :varargs], :void, **opts
      attach_function :xrap_msg_if_unmodified_since, [:pointer], :uint64, **opts
      attach_function :xrap_msg_set_if_unmodified_since, [:pointer, :uint64], :void, **opts
      attach_function :xrap_msg_if_match, [:pointer], :string, **opts
      attach_function :xrap_msg_set_if_match, [:pointer, :string, :varargs], :void, **opts
      attach_function :xrap_msg_status_text, [:pointer], :string, **opts
      attach_function :xrap_msg_set_status_text, [:pointer, :string, :varargs], :void, **opts
      attach_function :xrap_msg_test, [:bool], :void, **opts

      require_relative 'ffi/xrap_msg'
    end
  end
end

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
