/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
package org.zeromq.zebra;
import org.zeromq.czmq.*;

public class ZebHandler {
    static {
        try {
            System.loadLibrary ("zebrajni");
        }
        catch (Exception e) {
            System.exit (-1);
        }
    }
    public long self;
    /*
    Add a new offer this handler will handle. Returns 0 if successful,
    otherwise -1.                                                     
    The content type parameter is optional and is used to             
    filter requests upon their requested (GET) or provided (POST/PUT) 
    content's type. The content type parameter may be a regex. If the 
    request's content type does not match it is automatically rejected
    with the error code 406 (Not acceptable).                         
    */
    native static int __addOffer (long self, int method, String uri, String contentType);
    public int addOffer (Zactor self, int method, String uri, String contentType) {
        return __addOffer (self.self, method, uri, contentType);
    }
    /*
    Self test of this class.
    */
    native static void __test (boolean verbose);
    public static void test (boolean verbose) {
        __test (verbose);
    }
}
