/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
#ifndef Q_XRAP_TRAFFIC_H
#define Q_XRAP_TRAFFIC_H

#include "qzebra.h"

class QT_ZEBRA_EXPORT QXrapTraffic : public QObject
{
    Q_OBJECT
public:

    //  Copy-construct to return the proper wrapped c types
    QXrapTraffic (xrap_traffic_t *self, QObject *qObjParent = 0);

    //  Create a new empty xrap_traffic
    explicit QXrapTraffic (QObject *qObjParent = 0);

    //  Destroy a xrap_traffic instance
    ~QXrapTraffic ();

    //  Receive a xrap_traffic from the socket. Returns 0 if OK, -1 if
    //  there was an error. Blocks if there is no message waiting.    
    int recv (QZsock *input);

    //  Send the xrap_traffic to the output socket, does not destroy it
    int send (QZsock *output);

    //  Print contents of message to stdout
    void print ();

    //  Get the message routing id, as a frame
    QZframe * routingId ();

    //  Set the message routing id from a frame
    void setRoutingId (QZframe *routingId);

    //  Get the xrap_traffic message id
    int id ();

    //  Set the xrap_traffic message id
    void setId (int id);

    //  Get the xrap_traffic message id as printable text
    const QString command ();

    //  Get the address field
    const QString address ();

    //  Set the address field
    void setAddress (const QString &address);

    //  Get the timeout field
    quint32 timeout ();

    //  Set the timeout field
    void setTimeout (quint32 timeout);

    //  Get a copy of the content field
    QZmsg * content ();

    //  Get the content field and transfer ownership to caller
    QZmsg * getContent ();

    //  
    void setContent (QZmsg *contentP);

    //  Get the route field
    const QString route ();

    //  Set the route field
    void setRoute (const QString &route);

    //  Get the method field
    const QString method ();

    //  Set the method field
    void setMethod (const QString &method);

    //  Get the sender field
    QZuuid * sender ();

    //  Get the sender field and transfer ownership to caller
    QZuuid * getSender ();

    //  Set the sender field
    void setSender (QZuuid *senderP);

    //  Get the status_code field
    quint16 statusCode ();

    //  Set the status_code field
    void setStatusCode (quint16 statusCode);

    //  Get the status_reason field
    const QString statusReason ();

    //  Set the status_reason field
    void setStatusReason (const QString &statusReason);

    //  Self test of this class.
    static void test (bool verbose);

    xrap_traffic_t *self;
};
#endif //  Q_XRAP_TRAFFIC_H
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
