/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
#ifndef Q_ZEB_HANDLER_H
#define Q_ZEB_HANDLER_H

#include "qzwebrap.h"

class QT_ZWEBRAP_EXPORT QZebHandler : public QObject
{
    Q_OBJECT
public:

    //  Copy-construct to return the proper wrapped c types
    QZebHandler (zeb_handler_t *self, QObject *qObjParent = 0);

    //  Add a new offer this handler will handle. Returns 0 if successful,
    //  otherwise -1.                                                     
    static int addOffer (QZactor *self, int method, const QString &uri);

    //  Add a new accept type that this handler can deliver. May be a regular
    //  expression. Returns 0 if successfull, otherwise -1.                  
    static int addAccept (QZactor *self, const QString &accept);

    //  Self test of this class.
    static void test (bool verbose);

    zeb_handler_t *self;
};
#endif //  Q_ZEB_HANDLER_H
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
