/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
#ifndef Q_ZWEBRAP_H
#define Q_ZWEBRAP_H

#include <QObject>
#include <QString>
#include <zwebrap.h>

#if defined(Q_OS_WIN)
#  if !defined(QT_ZWEBRAP_EXPORT) && !defined(QT_ZWEBRAP_IMPORT)
#    define QT_ZWEBRAP_EXPORT
#  elif defined(QT_ZWEBRAP_IMPORT)
#    if defined(QT_ZWEBRAP_EXPORT)
#      undef QT_ZWEBRAP_EXPORT
#    endif
#    define QT_ZWEBRAP_EXPORT __declspec(dllimport)
#  elif defined(QT_ZWEBRAP_EXPORT)
#    undef QT_ZWEBRAP_EXPORT
#    define QT_ZWEBRAP_EXPORT __declspec(dllexport)
#  endif
#else
#  define QT_ZWEBRAP_EXPORT
#endif

//  Opaque class structures to allow forward references
class QZebHandler;
class QXrapMsg;
class QZwrClient;
class QZactor;
class QZmsg;
class QZhash;
class QZsock;
class QZuuid;
class QZframe;
class QZlist;

//  Public API classes
#include "qzebhandler.h"
#include "qxrapmsg.h"
#include "qzwrclient.h"
#include "qzactor.h"
#include "qzmsg.h"
#include "qzhash.h"
#include "qzsock.h"
#include "qzuuid.h"
#include "qzframe.h"
#include "qzlist.h"

#endif //  Q_ZWEBRAP_H
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
