/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
#include <stdio.h>
#include <stdlib.h>
#include <jni.h>
#include "zwebrap.h"
#include "../../native/include/org_zeromq_zwebrap_ZwrClient.h"

JNIEXPORT jlong JNICALL
Java_zwr_client__1_1new (JNIEnv *env, jclass c)
{
    jlong new_ = (jlong) zwr_client_new ();
    return new_;
}

JNIEXPORT void JNICALL
Java_zwr_client__1_1destroy (JNIEnv *env, jclass c, jlong self_p)
{
    zwr_client_destroy ((zwr_client_t **) &self_p);
}

JNIEXPORT void JNICALL
Java_zwr_client__1_1print (JNIEnv *env, jclass c, jlong self)
{
    zwr_client_print ((zwr_client_t *) self);
}

JNIEXPORT jlong JNICALL
Java_zwr_client__1_1actor (JNIEnv *env, jclass c, jlong self)
{
    jlong actor_ = (jlong) zwr_client_actor ((zwr_client_t *) self);
    return actor_;
}

JNIEXPORT jlong JNICALL
Java_zwr_client__1_1msgpipe (JNIEnv *env, jclass c, jlong self)
{
    jlong msgpipe_ = (jlong) zwr_client_msgpipe ((zwr_client_t *) self);
    return msgpipe_;
}

JNIEXPORT jboolean JNICALL
Java_zwr_client__1_1connected (JNIEnv *env, jclass c, jlong self)
{
    jboolean connected_ = (jboolean) zwr_client_connected ((zwr_client_t *) self);
    return connected_;
}

JNIEXPORT jint JNICALL
Java_zwr_client__1_1connect (JNIEnv *env, jclass c, jlong self, jstring endpoint, jint timeout, jstring address)
{
    char *endpoint_ = (char *) (*env)->GetStringUTFChars (env, endpoint, NULL);
    char *address_ = (char *) (*env)->GetStringUTFChars (env, address, NULL);
    jint connect_ = (jint) zwr_client_connect ((zwr_client_t *) self, endpoint_, (uint32_t) timeout, address_);
    (*env)->ReleaseStringUTFChars (env, endpoint, endpoint_);
    (*env)->ReleaseStringUTFChars (env, address, address_);
    return connect_;
}

JNIEXPORT jint JNICALL
Java_zwr_client__1_1set_handler (JNIEnv *env, jclass c, jlong self, jstring method, jstring route)
{
    char *method_ = (char *) (*env)->GetStringUTFChars (env, method, NULL);
    char *route_ = (char *) (*env)->GetStringUTFChars (env, route, NULL);
    jint set_handler_ = (jint) zwr_client_set_handler ((zwr_client_t *) self, method_, route_);
    (*env)->ReleaseStringUTFChars (env, method, method_);
    (*env)->ReleaseStringUTFChars (env, route, route_);
    return set_handler_;
}

JNIEXPORT jint JNICALL
Java_zwr_client__1_1request (JNIEnv *env, jclass c, jlong self, jint timeout, jlong content_p)
{
    jint request_ = (jint) zwr_client_request ((zwr_client_t *) self, (uint32_t) timeout, (zmsg_t **) &content_p);
    return request_;
}

JNIEXPORT jint JNICALL
Java_zwr_client__1_1deliver (JNIEnv *env, jclass c, jlong self, jlong sender, jlong content_p)
{
    jint deliver_ = (jint) zwr_client_deliver ((zwr_client_t *) self, (zuuid_t *) sender, (zmsg_t **) &content_p);
    return deliver_;
}

JNIEXPORT jlong JNICALL
Java_zwr_client__1_1recv (JNIEnv *env, jclass c, jlong self)
{
    jlong recv_ = (jlong) zwr_client_recv ((zwr_client_t *) self);
    return recv_;
}

JNIEXPORT jstring JNICALL
Java_zwr_client__1_1command (JNIEnv *env, jclass c, jlong self)
{
    char *command_ = (char *) zwr_client_command ((zwr_client_t *) self);
    jstring string = (*env)->NewStringUTF (env, command_);
    return string;
}

JNIEXPORT jint JNICALL
Java_zwr_client__1_1status (JNIEnv *env, jclass c, jlong self)
{
    jint status_ = (jint) zwr_client_status ((zwr_client_t *) self);
    return status_;
}

JNIEXPORT jstring JNICALL
Java_zwr_client__1_1reason (JNIEnv *env, jclass c, jlong self)
{
    char *reason_ = (char *) zwr_client_reason ((zwr_client_t *) self);
    jstring string = (*env)->NewStringUTF (env, reason_);
    return string;
}

JNIEXPORT jlong JNICALL
Java_zwr_client__1_1sender (JNIEnv *env, jclass c, jlong self)
{
    jlong sender_ = (jlong) zwr_client_sender ((zwr_client_t *) self);
    return sender_;
}

JNIEXPORT jlong JNICALL
Java_zwr_client__1_1content (JNIEnv *env, jclass c, jlong self)
{
    jlong content_ = (jlong) zwr_client_content ((zwr_client_t *) self);
    return content_;
}

JNIEXPORT void JNICALL
Java_zwr_client__1_1test (JNIEnv *env, jclass c, jboolean verbose)
{
    zwr_client_test ((bool) verbose);
}

