/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
#include <stdio.h>
#include <stdlib.h>
#include <jni.h>
#include "zebra.h"
#include "org_zeromq_zebra_ZebHandler.h"

JNIEXPORT jint JNICALL
Java_org_zeromq_zebra_ZebHandler__1_1addOffer (JNIEnv *env, jclass c, jlong self, jint method, jstring uri)
{
    char *uri_ = (char *) (*env)->GetStringUTFChars (env, uri, NULL);
    jint add_offer_ = (jint) zeb_handler_add_offer ((zactor_t *) (intptr_t) self, (int) method, uri_);
    (*env)->ReleaseStringUTFChars (env, uri, uri_);
    return add_offer_;
}

JNIEXPORT jint JNICALL
Java_org_zeromq_zebra_ZebHandler__1_1addAccept (JNIEnv *env, jclass c, jlong self, jstring accept)
{
    char *accept_ = (char *) (*env)->GetStringUTFChars (env, accept, NULL);
    jint add_accept_ = (jint) zeb_handler_add_accept ((zactor_t *) (intptr_t) self, accept_);
    (*env)->ReleaseStringUTFChars (env, accept, accept_);
    return add_accept_;
}

JNIEXPORT void JNICALL
Java_org_zeromq_zebra_ZebHandler__1_1test (JNIEnv *env, jclass c, jboolean verbose)
{
    zeb_handler_test ((bool) verbose);
}

