/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
#include <stdio.h>
#include <stdlib.h>
#include <jni.h>
#include "zebra.h"
#include "org_zeromq_zebra_ZebHandler.h"

JNIEXPORT jint JNICALL
Java_org_zeromq_zebra_ZebHandler__1_1addOffer (JNIEnv *env, jclass c, jlong self, jint method, jstring uri, jstring content_type)
{
    char *uri_ = (char *) (*env)->GetStringUTFChars (env, uri, NULL);
    char *content_type_ = (char *) (*env)->GetStringUTFChars (env, content_type, NULL);
    jint add_offer_ = (jint) zeb_handler_add_offer ((zactor_t *) (intptr_t) self, (int) method, uri_, content_type_);
    (*env)->ReleaseStringUTFChars (env, uri, uri_);
    (*env)->ReleaseStringUTFChars (env, content_type, content_type_);
    return add_offer_;
}

JNIEXPORT void JNICALL
Java_org_zeromq_zebra_ZebHandler__1_1test (JNIEnv *env, jclass c, jboolean verbose)
{
    zeb_handler_test ((bool) verbose);
}

