/*  =========================================================================
    zwebrap - ZWEBRAP wrapper

    Copyright (c) the Contributors as noted in the AUTHORS file.
    This file is part of CZMQ, the high-level C binding for 0MQ:
    http://czmq.zeromq.org.

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
    =========================================================================
*/

#ifndef zwebrap_library_H_INCLUDED
#define zwebrap_library_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <czmq.h>
#include <microhttpd.h>
#include <curl/curl.h>

//  ZWEBRAP version macros for compile-time API detection

#define ZWEBRAP_VERSION_MAJOR 1
#define ZWEBRAP_VERSION_MINOR 0
#define ZWEBRAP_VERSION_PATCH 0

#define ZWEBRAP_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define ZWEBRAP_VERSION \
    ZWEBRAP_MAKE_VERSION(ZWEBRAP_VERSION_MAJOR, ZWEBRAP_VERSION_MINOR, ZWEBRAP_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined LIBZWEBRAP_STATIC
#       define ZWEBRAP_EXPORT
#   elif defined LIBZWEBRAP_EXPORTS
#       define ZWEBRAP_EXPORT __declspec(dllexport)
#   else
#       define ZWEBRAP_EXPORT __declspec(dllimport)
#   endif
#else
#   define ZWEBRAP_EXPORT
#endif

//  Opaque class structures to allow forward references
typedef struct _xrap_msg_t xrap_msg_t;
#define XRAP_MSG_T_DEFINED


//  Public API classes
#include "xrap_msg.h"

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
