################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################

if (NOT MSVC)
    include(FindPkgConfig)
    pkg_check_modules(PC_ZEBRA "libzebra")
    if (NOT PC_ZEBRA_FOUND)
        pkg_check_modules(PC_ZEBRA "libzebra")
    endif (NOT PC_ZEBRA_FOUND)
    if (PC_ZEBRA_FOUND)
        # some libraries install the headers is a subdirectory of the include dir
        # returned by pkg-config, so use a wildcard match to improve chances of finding
        # headers and SOs.
        set(PC_ZEBRA_INCLUDE_HINTS ${PC_ZEBRA_INCLUDE_DIRS} ${PC_ZEBRA_INCLUDE_DIRS}/*)
        set(PC_ZEBRA_LIBRARY_HINTS ${PC_ZEBRA_LIBRARY_DIRS} ${PC_ZEBRA_LIBRARY_DIRS}/*)
    endif(PC_ZEBRA_FOUND)
endif (NOT MSVC)

find_path (
    ZEBRA_INCLUDE_DIRS
    NAMES zebra.h
    HINTS ${PC_ZEBRA_INCLUDE_HINTS}
)

find_library (
    ZEBRA_LIBRARIES
    NAMES zebra
    HINTS ${PC_ZEBRA_LIBRARY_HINTS}
)

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(
    ZEBRA
    REQUIRED_VARS ZEBRA_LIBRARIES ZEBRA_INCLUDE_DIRS
)
mark_as_advanced(
    ZEBRA_FOUND
    ZEBRA_LIBRARIES ZEBRA_INCLUDE_DIRS
)

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
